
    -- Init Appartements
    -- apparts = {}
    -- len = 0
    -- for i=0,6 do
    --     appart = {}
    --     appart.width = love.math.random(3, 6)
    --     appart.height= love.math.random(4, 15)
    --     if i ~= 0 then
    --         appart.x = apparts[i].x + apparts[i].width * 10 + love.math.random(1,2) * 10 
    --         len = len + appart.x
    --     else
    --         appart.x = 0
    --     end
    --     appart.y = dimy + 10
    --     table.insert(apparts, appart)
    -- end

    
    -- for i, v in ipairs(apparts) do
    --     v.x = v.x - camera.x
    --     if v.x < 0 then
    --         table.remove(apparts, i);
    --     end
    -- end  
    -- love.graphics.print(table.getn(apparts), 0, 0);
    -- Appartement
    -- for i, v in ipairs (apparts) do
    --     draw_appart(v.x, v.y, v.width, v.height)
    -- end
    -- Fin Appartement